### ISSUE TITLE
Interact script is missing

### ISSUE THREAD

**Issue by lfdharo** [andreamad8/PPCM#2]
Hi, the main.py file is requesting the interact.py script to work. Besides, the dialogGPT_discr.py also requires importing some scripts from the data.emocap and data.empathetic folders which are not included.

**Comment by andreamad8** [comment]
Hi 

we did not include data.emocap and data.empathetic  because at the end we didn't use it in this paper experiments. If you want some empathetic generation from PPCC please refer to https://github.com/HLTCHKUST/adapterbot, where we release the PPLM generate responses for different emotions. 

I have just pushed the interactive script, for both PPLM and Adapters. Notice that this interactive script is very rudimental. We have a more advanced version at https://github.com/HLTCHKUST/adapterbot

I hope this helps. 

Andrea
